# Generated by Django 4.2.14 on 2024-07-11 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("curso", models.CharField(max_length=100)),
                ("nota1", models.FloatField()),
                ("nota2", models.FloatField()),
                ("fecha_reg", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
